sudo: required

services:
- docker

addons:
  apt:
    packages:
    - docker-ce

language: java
jdk:
- oraclejdk8
- openjdk8
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"

script:
- "./gradlew --daemon"
- "./gradlew assemble -x test --parallel"
- "./gradlew test --info"
- "./gradlew jacocoTestReport"
- "bash <(curl -s https://codecov.io/bash)"
- "./gradlew sonarqube \
    -Dsonar.organization=soramitsu \
    -Dsonar.projectKey=testcontainers-iroha \
    -Dsonar.host.url=https://sonar.soramitsu.co.jp \
    -Dsonar.login=${SONAR_TOKEN}"
